### ISSUE TITLE
Automatically minimise files unselected

### ISSUE THREAD

**Issue by intellix** [picheli20/github-code-tree#1]
My biggest issue with Github not having a tree-view when reviewing is that on large reviews the UI becomes unusable because there's so much code to render and probably a lot of DOM. I think it'd be awesome if this plugin either automatically minimised and handled the expanding of the selected file, or just outright hid those sections of the DOM so reviews become speedy

![screenshot 2017-09-16 21 47 03](https://user-images.githubusercontent.com/1162531/30515474-a5434124-9b28-11e7-93c0-fb3187c57650.png)

Awesome plugin though!

**Comment by picheli20** [comment]
Fixed on https://github.com/picheli20/github-code-tree/commit/cc6ecbda7520ca9651f2b50e53e83068ebbbb4f1
