### ISSUE TITLE
Expand large diffs by default

### ISSUE THREAD

**Issue by danmoseley** [picheli20/github-code-tree#12]
Sometimes github collapses some files in the PR because "large diffs are not expanded by default"

Sometimes I want to see them all anyway, eg., because I want to search on the page, or because I just do.

Can this extension expand them all? At first I thought it could, as there is a Collapse All, but when I click Expand All it doesn't expand those ones.

**Comment by picheli20** [comment]
Do you mean those cases?
![screen shot 2018-08-29 at 11 18 09](https://user-images.githubusercontent.com/3877606/44778435-3b5ccf80-ab7d-11e8-8111-7577c89aa270.png)

I think we can add a option to "Load diff" automatically

**Comment by picheli20** [comment]
Done on https://github.com/picheli20/github-code-tree/commit/32dc8cc3ff7a3c4ecf8b585f6836568f97834803 it's available on v1.1.0

**Comment by danmoseley** [comment]
Nice - thanks @picheli20 !
