### ISSUE TITLE
"Collapse all" no longer collapsing files

### ISSUE THREAD

**Issue by tquetano-r7** [picheli20/github-code-tree#13]
The `Open` / `Close` buttons still work, but the `Expand all` / `Collapse all` button no longer does.

**Comment by tquetano-r7** [comment]
So interesting ... once you toggle the file once, it will respect the button. I think this may be because of the selector, which looks for `open Details--on`, but on initial load the class name is set to `Details--on open` (reverse order), so the selector may not be picking that up? I say that because once toggled, the "order" of those two classes match the selector and then it works.

**Comment by picheli20** [comment]
Fixed on https://github.com/picheli20/github-code-tree/commit/860f0ab793a23af0a43350d81a12828b4c0848df
