### ISSUE TITLE
Enterprise Github

### ISSUE THREAD

**Issue by pyella** [picheli20/github-code-tree#14]
Very helpful extension! However it doesn't work on enterprise version of Github I use at work.

**Comment by warrenscipio** [comment]
So I too thought this would be super useful and tested, this is an already built extenstion we can actually pull it down and edit it ourselves as a temp fix to this problem. Here is another plugins post asking for a the same thing https://github.com/berzniz/github_pr_tree/issues/3#issuecomment-422906872. For this plugin we will need to do step 1,4,5. 

On top of those changes you will need to go into the `index.js` file search for the string `github` and change the regex portion to`github[\.]?[-a-zA-Z0-9]*\.com` I think this will accept any company as long as the url name doesn't have special characters, you can also just add your company name to the url `github.mycompany\.com` just like you did in the manifest file.

**Comment by picheli20** [comment]
I think a solution is to make this regex that @warrenscipio configurable, so then you can "activate" in any page.

**Comment by chvarunkumar1994** [comment]
It would be nice if the readme has documentation on how to set up the plugin for an enterprise version of Github.
