### ISSUE TITLE
Support GitHub Enterprise hosts not on .com TLD

### ISSUE THREAD

**Issue by gregbradley** [picheli20/github-code-tree#16]
Our GitHub Enterprise instance is hosted on a domain with a private TLD, i.e. `github.source.internal.mycompany` and therefore the extension is not activated via the manifest and the regexes in `index.js` won't recognise it also.

**Comment by chvarunkumar1994** [comment]
Is there a workaround for this?

**Comment by picheli20** [comment]
I've just fixed, will be releasing it soon

**Comment by picheli20** [comment]
Released, basically now you have a new field that you can add the regex as you wish :) 

Layout is a bit messy, but will organize it soon

![screenshot from 2019-01-23 18-50-43](https://user-images.githubusercontent.com/3877606/51626432-cfba3b00-1f3f-11e9-81ee-f4f85a41e6d9.png)
