### ISSUE TITLE
The extension seems to be broken

### ISSUE THREAD

**Issue by cardil** [picheli20/github-code-tree#18]
![image](https://user-images.githubusercontent.com/540893/52382233-abe51200-2a74-11e9-9165-25627f606e51.png)

See attached image. It looks like the styles have changed and it now doesn't look like it suppose to.

**Comment by Hacksore** [comment]
This seems related to #15 and unified diff. I think updating the styles to account for unified diff could work.

**Comment by picheli20** [comment]
I think what @Hacksore said should work, now it's a bit hard for me to check, if someone wants to make a PR feel free :)

**Comment by picheli20** [comment]
Was fixed on the latest version :) @cardil please let me know if still not working
