### ISSUE TITLE
publish a new version

### ISSUE THREAD

**Issue by regevbr** [picheli20/github-code-tree#28]
@picheli20  You last published the extension in April 19, and there have been some additions to the code since that I need (the refresh button for example). Can you please publish a new version?

**Comment by picheli20** [comment]
@regevbr I've just merged one features, so a new MR, will create a version today

**Comment by picheli20** [comment]
@regevbr actaully is my bad - I tough I've published it, but just saw that It was refused. It needs to justify now why we use `activeTab`

**Comment by regevbr** [comment]
Yeah they recently imposed a lot more restrictions on extensions...
