### ISSUE TITLE
Chrome Addon is still in 1.2.1

### ISSUE THREAD

**Issue by mrudelle** [picheli20/github-code-tree#31]
Here: https://chrome.google.com/webstore/detail/tree-explorer-for-github/caffoilocbbhnkdlpdcfanpbeholjdii?hl=en

I had to install it manually to have the latest features like refresh for big PRs

**Comment by picheli20** [comment]
Hi @mrudelle 

Thanks for letting me know, I had some issues on google store. I've just send the correct version for review,

**Comment by picheli20** [comment]
Released :)
